# Generated by Django 6.1.1 on 2026-09-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('client_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=20)),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='material',
            name='expire_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_key1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_key2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_key3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_key4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_key5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_val1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_val2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_val3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_val4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spec_val5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted / Confirmed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='base.client'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='base.client'),
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='base.unitofmeasure')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='base.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Unit Conversion',
                'verbose_name_plural': 'Unit Conversions',
                'unique_together': {('from_uom', 'to_uom')},
            },
        ),
        migrations.DeleteModel(
            name='BusinessPartner',
        ),
    ]
