# Generated by Django 6.1.1 on 2026-10-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcategory',
            name='parent',
        ),
    ]
