# Generated by Django 6.1.1 on 2026-10-08 15:54

import versatileimagefield.fields
from django.contrib.staticfiles import finders
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import migrations
from django.db.models import Q

PLACEHOLDER_ICON = "images/categories/placeholder.jpg"
STATIC_PLACEHOLDER = "assets/images/categories/placeholder.jpg"


def setup_placeholder_icon(apps, schema_editor):
    """Copy the placeholder into media and point icon-less categories at it.

    `icon` now defaults to a media path, so the file itself must live in
    storage for `.url` to resolve in every environment (dev, tests, PA).
    """
    if not default_storage.exists(PLACEHOLDER_ICON):
        source_path = finders.find(STATIC_PLACEHOLDER)
        if source_path:
            with open(source_path, "rb") as f:
                default_storage.save(PLACEHOLDER_ICON, ContentFile(f.read()))

    MaterialCategory = apps.get_model("base", "MaterialCategory")
    MaterialCategory.objects.filter(
        Q(icon="") | Q(icon__isnull=True)
    ).update(icon=PLACEHOLDER_ICON)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_copy_category_icons_to_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/categories/covers'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/categories/placeholder.jpg', null=True, upload_to='images/categories'),
        ),
        migrations.RunPython(setup_placeholder_icon, migrations.RunPython.noop),
    ]
