# Generated by Django 6.1.1 on 2026-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_materialcategory_image_alter_materialcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='feature_reason',
            field=models.CharField(blank=True, choices=[('OFFER', 'Offer'), ('LIMITED_TIME', 'Limited Time'), ('SPECIAL', 'Special')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
